kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"monster:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"monster\")].image"}]
  name: monster
  namespace: {{ .Values.namespace }}-monsters
  labels:
    app: monster
    app.kubernetes.io/component: monster
    app.kubernetes.io/instance: monster
spec:
  replicas: {{ .Values.monsterReplicas }}
  selector:
    matchLabels:
      deployment: monster
  template:
    metadata:
      labels:
        deployment: monster
    spec:
      containers:
        - name: monster
          image: {{ .Values.images.monsterImage }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      serviceAccountName: monster-deployment
      serviceAccount: monster-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%