{{- range $user := .Values.users }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ $user | lower }}

---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ $user | lower }}-monsters

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $user }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: admins
{{- end }}
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: admins
users:
{{ toYaml .Values.users | indent 2}}